[package]
name = "tsr-execute"
description = "The tsc command line: tsgo's internal/execute"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tsr-core.workspace = true
tsr-compiler.workspace = true
tsr-checker.workspace = true
tsr-diagnostics.workspace = true
tsr-module.workspace = true
tsr-parser.workspace = true
tsr-path.workspace = true
tsr-tsoptions.workspace = true
tsr-vfs.workspace = true

[lints]
workspace = true
