//! Generate the embedded library table for `bundled.rs`.
//!
//! Native `internal/bundled/generate.go` writes `embed_generated.go`: one
//! `//go:embed libs/<name>` per bundled file and `LibNames` sorted by name.
//! This is the same table, regenerated at build time from the pinned
//! submodule so it cannot drift from the libraries it embeds.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"));
    let libs = manifest.join("../../vendor/typescript-go/internal/bundled/libs");
    println!("cargo:rerun-if-changed={}", libs.display());

    let mut names: Vec<String> = std::fs::read_dir(&libs)
        .unwrap_or_else(|error| panic!("reading {}: {error}", libs.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().into_string().ok()?;
            (entry.file_type().ok()?.is_file() && name.ends_with(".d.ts")).then_some(name)
        })
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no bundled libraries in {}", libs.display());

    let mut table =
        String::from("/// Generated by `build.rs`: `(name, contents)`, sorted by name.\n");
    table.push_str("pub(crate) static EMBEDDED_LIBS: &[(&str, &str)] = &[\n");
    for name in &names {
        let path = libs.join(name).canonicalize().expect("listed library exists");
        writeln!(table, "    ({name:?}, include_str!({:?})),", path.display().to_string())
            .expect("write to string");
    }
    table.push_str("];\n");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets it"));
    std::fs::write(out.join("bundled_libs.rs"), table).expect("write the generated table");
}
