//! Generates `crates/tsr-ast/src/generated/kind.rs`.
//!
//! `SyntaxKind` is the spine of AST conformance. TypeScript assigns meaning to the
//! *ordinal values* — `isAssignmentOperator` is a range check, not a set
//! membership test — so both the names and their order are load-bearing. We emit
//! an explicit discriminant for every variant so that a reordering upstream
//! becomes a visible diff rather than a silent renumbering.

use std::fmt::Write as _;

use anyhow::Result;
use convert_case::{Case, Casing};

use crate::ast_json::{AstDefinition, KindAlias, KindElement};

/// Rust keywords that can appear as kind names and need raw-identifier escaping.
fn escape_ident(name: &str) -> String {
    match name {
        "As" => "As".to_string(),
        _ => name.to_string(),
    }
}

/// Generate the `SyntaxKind` enum, its markers, and its alias predicates.
pub fn generate(ast: &AstDefinition) -> Result<String> {
    let mut out = String::with_capacity(64 * 1024);
    let elements = ast.kinds.kind_names();

    out.push_str(
        "//! The `SyntaxKind` enum.\n\
         //!\n\
         //! @generated by `cargo xtask codegen` from\n\
         //! `vendor/typescript-go/_scripts/ast.json`. Do not edit by hand.\n\
         //!\n\
         //! Corresponds to typescript-go's `ast.Kind`\n\
         //! (`internal/ast/kind_generated.go`), which is generated from the same\n\
         //! source. Discriminants are written explicitly because TypeScript treats\n\
         //! kind ordering as semantic: several predicates below are range checks.\n\n",
    );

    // ---- the enum -------------------------------------------------------
    out.push_str(
        "/// A TypeScript syntax kind.\n\
         ///\n\
         /// Ordinal values match typescript-go and the TypeScript compiler exactly;\n\
         /// see the conformance test in `tests/kind_conformance.rs`.\n\
         #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]\n\
         #[repr(u16)]\n\
         #[allow(missing_docs, clippy::doc_markdown)]\n\
         pub enum SyntaxKind {\n",
    );
    // Walk the raw element list so upstream's section comments are preserved as
    // headers, while only kinds consume a discriminant.
    let mut discriminant = 0usize;
    for element in &ast.kinds.elements {
        match element {
            KindElement::Comment { comment } => {
                writeln!(out, "\n    // {comment}")?;
            }
            KindElement::Kind(name) => {
                writeln!(out, "    {} = {discriminant},", escape_ident(name))?;
                discriminant += 1;
            }
            KindElement::NamedKind { name, comment } => {
                if let Some(comment) = comment {
                    writeln!(out, "    /// {comment}")?;
                }
                writeln!(out, "    {} = {discriminant},", escape_ident(name))?;
                discriminant += 1;
            }
        }
    }
    out.push_str("}\n\n");

    // ---- count + conversions -------------------------------------------
    writeln!(
        out,
        "impl SyntaxKind {{\n    \
         /// Number of distinct syntax kinds.\n    \
         ///\n    \
         /// Corresponds to typescript-go's `KindCount`.\n    \
         pub const COUNT: u16 = {};\n",
        elements.len()
    )?;

    // Every kind, in order — lets tests assert the full list without reflection.
    out.push_str("    /// Every syntax kind, in declaration order.\n");
    writeln!(out, "    pub const ALL: [Self; {}] = [", elements.len())?;
    for name in &elements {
        writeln!(out, "        Self::{},", escape_ident(name))?;
    }
    out.push_str("    ];\n\n");

    // ---- markers --------------------------------------------------------
    out.push_str("    // Named markers. Corresponds to the `Kind*` aliases upstream.\n");
    for marker in &ast.kinds.markers {
        writeln!(
            out,
            "    /// Marker alias for [`SyntaxKind::{}`].\n    \
             pub const {}: Self = Self::{};",
            resolve_marker(ast, &marker.value),
            marker.name.to_case(Case::UpperSnake),
            resolve_marker(ast, &marker.value),
        )?;
    }
    out.push('\n');

    // ---- name + roundtrip ----------------------------------------------
    out.push_str(
        "    /// The kind's upstream name, e.g. `\"BinaryExpression\"`.\n    \
         ///\n    \
         /// Used by the conformance harness to diff against Go's `Kind.String()`.\n    \
         #[must_use]\n    \
         pub const fn name(self) -> &'static str {\n        \
         match self {\n",
    );
    for name in &elements {
        writeln!(out, "            Self::{} => \"{name}\",", escape_ident(name))?;
    }
    out.push_str("        }\n    }\n\n");

    out.push_str(
        "    /// Convert from a raw discriminant, returning `None` if out of range.\n    \
         #[must_use]\n    \
         pub const fn from_u16(value: u16) -> Option<Self> {\n        \
         if value < Self::COUNT {\n            \
         // SAFETY: `SyntaxKind` is `repr(u16)` with contiguous discriminants\n            \
         // `0..COUNT`, and `value` was just bounds-checked against `COUNT`.\n            \
         Some(unsafe { std::mem::transmute::<u16, Self>(value) })\n        \
         } else {\n            None\n        }\n    }\n\n",
    );

    // ---- alias predicates ----------------------------------------------
    for (alias_name, alias) in &ast.kinds.aliases {
        let fn_name = format!("is_{}", strip_syntax_kind_suffix(alias_name).to_case(Case::Snake));
        let body = match alias {
            KindAlias::Range { range } => {
                let [first, last] = range;
                format!(
                    "        (self as u16) >= (Self::{} as u16) && (self as u16) <= (Self::{} as u16)",
                    resolve_marker(ast, first),
                    resolve_marker(ast, last),
                )
            }
            KindAlias::List(items) => {
                // A list may name concrete kinds, markers, or *other aliases*
                // (`AdditiveOperatorOrHigher` includes
                // `MultiplicativeOperatorOrHigher`). Nested aliases delegate to
                // their own predicate rather than being flattened, so the
                // generated code stays readable and stays in sync automatically.
                let mut variants = Vec::new();
                let mut nested = Vec::new();
                for item in items {
                    if ast.kinds.aliases.contains_key(item) {
                        nested.push(format!(
                            "self.is_{}()",
                            strip_syntax_kind_suffix(item).to_case(Case::Snake)
                        ));
                    } else {
                        variants.push(format!("Self::{}", resolve_marker(ast, item)));
                    }
                }
                let mut terms = Vec::new();
                if !variants.is_empty() {
                    terms.push(format!("matches!(self, {})", variants.join("\n            | ")));
                }
                terms.extend(nested);
                format!("        {}", terms.join("\n            || "))
            }
        };
        writeln!(
            out,
            "    /// Whether this kind belongs to the `{alias_name}` group.\n    \
             #[must_use]\n    \
             pub const fn {fn_name}(self) -> bool {{\n{body}\n    }}\n"
        )?;
    }

    out.push_str("}\n\n");

    // ---- Display --------------------------------------------------------
    out.push_str(
        "impl std::fmt::Display for SyntaxKind {\n    \
         fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n        \
         f.write_str(self.name())\n    }\n}\n",
    );

    Ok(out)
}

/// Marker names are referenced in ranges by their alias name (`FirstPunctuation`);
/// resolve them to the concrete kind variant they point at.
fn resolve_marker(ast: &AstDefinition, name: &str) -> String {
    escape_ident(ast.kinds.resolve_marker(name))
}

/// `TriviaSyntaxKind` -> `Trivia`, so the predicate reads `is_trivia`.
fn strip_syntax_kind_suffix(name: &str) -> &str {
    name.strip_suffix("SyntaxKind").unwrap_or(name)
}
