//! Generates `crates/tsr-scanner/src/generated/unicode.rs`.
//!
//! ECMAScript identifier code-point tables: `ID_Start` (+`Other_ID_Start`) and
//! `ID_Continue` (+`Other_ID_Continue`, plus the Start set), per
//! [UAX #31](http://www.unicode.org/reports/tr31/).
//!
//! # Why this reads generated Go rather than the Unicode data
//!
//! This is the one deliberate exception to rule 1 in
//! `docs/adr/0007-generated-code-policy.md`. Upstream generates from the
//! `@unicode/unicode-15.1.0` npm package, which is not vendored — but the
//! *generated tables* are. Transcoding them pins us to exactly TypeScript's
//! Unicode version.
//!
//! The alternative, the `unicode-id-start` crate, tracks whatever Unicode version
//! it was built against. That would diverge from TypeScript on rare code points
//! and surface years later as a single inexplicable conformance failure. Being
//! pinned to the same version as the oracle is worth more here than avoiding a
//! transcode step.

use std::fmt::Write as _;

use anyhow::{Context, Result, bail};

/// An inclusive code-point range with a stride.
///
/// Go's `unicode.Range16`/`Range32` carry a stride, so `{0xAA, 0xB5, 11}` means
/// "0xAA and 0xB5" rather than the whole span. Flattening strides at generation
/// time would multiply the table size; we keep them and handle stride at lookup.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Range {
    lo: u32,
    hi: u32,
    stride: u32,
}

/// Parse the two `unicode.RangeTable` values out of upstream's generated Go.
fn parse_tables(source: &str) -> Result<Vec<(String, Vec<Range>)>> {
    let mut tables = Vec::new();
    let mut current: Option<(String, Vec<Range>)> = None;

    for line in source.lines() {
        let trimmed = line.trim();

        if let Some(rest) = trimmed.strip_prefix("var ") {
            if let Some(name) = rest.split_whitespace().next() {
                if let Some((name, table)) = current.take() {
                    tables.push((name, table));
                }
                current = Some((name.to_string(), Vec::new()));
            }
            continue;
        }

        // `{0x41, 0x5A, 1},`
        if let Some(body) = trimmed.strip_prefix('{').and_then(|s| s.strip_suffix("},")) {
            let parts: Vec<&str> = body.split(',').map(str::trim).collect();
            if parts.len() != 3 {
                continue;
            }
            let parse = |s: &str| -> Result<u32> {
                let s = s.strip_prefix("0x").unwrap_or(s);
                u32::from_str_radix(s, 16).with_context(|| format!("parsing code point {s:?}"))
            };
            let range = Range {
                lo: parse(parts[0])?,
                hi: parse(parts[1])?,
                stride: parts[2]
                    .parse()
                    .with_context(|| format!("parsing stride {:?}", parts[2]))?,
            };
            if let Some((_, table)) = current.as_mut() {
                table.push(range);
            }
        }
    }

    if let Some((name, table)) = current {
        tables.push((name, table));
    }
    Ok(tables)
}

/// Generate the identifier tables and their lookup functions.
pub fn generate(go_source: &str) -> Result<String> {
    let tables = parse_tables(go_source)?;

    let find = |want: &str| -> Result<&Vec<Range>> {
        tables
            .iter()
            .find(|(name, _)| name == want)
            .map(|(_, t)| t)
            .with_context(|| format!("table {want} not found in identifier_parts_generated.go"))
    };

    let start = find("unicodeESNextIdentifierStart")?;
    let part = find("unicodeESNextIdentifierPart")?;

    // A truncated parse would silently narrow what counts as an identifier, which
    // is close to undetectable by inspection.
    if start.len() < 500 || part.len() < 500 {
        bail!(
            "suspiciously small tables (start={}, part={}); the Go parser is probably broken",
            start.len(),
            part.len()
        );
    }

    let mut out = String::with_capacity(128 * 1024);
    out.push_str(
        "//! Unicode identifier tables for ECMAScript.\n\
         //!\n\
         //! @generated by `cargo xtask codegen` from typescript-go's\n\
         //! `internal/stringutil/identifier_parts_generated.go`. Do not edit by hand.\n\
         //!\n\
         //! Unicode 15.1.0, matching TypeScript exactly. See\n\
         //! `docs/adr/0007-generated-code-policy.md` for why this transcodes\n\
         //! upstream's generated tables rather than the Unicode data directly.\n\n\
         /// An inclusive code-point range with a stride.\n\
         ///\n\
         /// `(0xAA, 0xB5, 11)` means 0xAA and 0xB5 only — not the span between.\n\
         pub type Range = (u32, u32, u32);\n\n",
    );

    let mut emit = |name: &str, doc: &str, ranges: &[Range]| -> Result<()> {
        writeln!(out, "/// {doc}")?;
        writeln!(out, "pub static {name}: &[Range] = &[")?;
        for r in ranges {
            writeln!(out, "    (0x{:X}, 0x{:X}, {}),", r.lo, r.hi, r.stride)?;
        }
        out.push_str("];\n\n");
        Ok(())
    };

    emit(
        "ID_START",
        "Code points valid as the first character of an identifier (`ID_Start` plus `Other_ID_Start`).",
        start,
    )?;
    emit(
        "ID_CONTINUE",
        "Code points valid after the first character (`ID_Continue`, `Other_ID_Continue`, and the start set).",
        part,
    )?;

    out.push_str(
        "/// Whether `table` contains `cp`.\n\
         ///\n\
         /// Binary search over the range list, then a stride check. Ranges are\n\
         /// sorted and disjoint, which the tests assert rather than assume.\n\
         #[must_use]\n\
         pub fn contains(table: &[Range], cp: u32) -> bool {\n    \
         let index = table.partition_point(|&(lo, _, _)| lo <= cp);\n    \
         if index == 0 {\n        return false;\n    }\n    \
         let (lo, hi, stride) = table[index - 1];\n    \
         if cp > hi {\n        return false;\n    }\n    \
         // stride 1 is overwhelmingly the common case.\n    \
         stride == 1 || (cp - lo) % stride == 0\n}\n",
    );

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_ranges_with_strides() {
        let source = "\
var unicodeESNextIdentifierStart = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x41, 0x5A, 1},
		{0xAA, 0xB5, 11},
	},
	R32: []unicode.Range32{
		{0x10000, 0x1000B, 1},
	},
}
";
        let tables = parse_tables(source).expect("parses");
        assert_eq!(tables.len(), 1);
        assert_eq!(tables[0].0, "unicodeESNextIdentifierStart");
        assert_eq!(
            tables[0].1,
            vec![
                Range { lo: 0x41, hi: 0x5A, stride: 1 },
                Range { lo: 0xAA, hi: 0xB5, stride: 11 },
                Range { lo: 0x10000, hi: 0x1000B, stride: 1 },
            ]
        );
    }

    #[test]
    fn r16_and_r32_are_merged_into_one_table() {
        // Go splits by width for compactness; a single sorted list is simpler and
        // the ordering is preserved because R32 always follows R16.
        let source = "\
var t = &unicode.RangeTable{
	R16: []unicode.Range16{
		{0x41, 0x5A, 1},
	},
	R32: []unicode.Range32{
		{0x10000, 0x1000B, 1},
	},
}
";
        let tables = parse_tables(source).expect("parses");
        assert_eq!(tables[0].1.len(), 2);
        assert!(tables[0].1[0].lo < tables[0].1[1].lo, "must stay sorted across the split");
    }
}
