//! Maintenance tasks for tsr.
//!
//! ```text
//! cargo xtask codegen    regenerate crates/tsr-ast/src/generated
//! ```
//!
//! Codegen reads `vendor/typescript-go/_scripts/ast.json`, the same
//! schema-validated definition upstream uses to generate its own Go AST. Deriving
//! our AST from that file is what makes conformance a build property rather than a
//! claim: when upstream adds a node kind, regeneration picks it up and the
//! conformance tests fail until we do.

mod ast_json;
mod gen_kind;
mod gen_nodes;

use std::{fs, path::PathBuf};

use anyhow::{Context, Result, bail};

use ast_json::AstDefinition;

fn main() -> Result<()> {
    let task = std::env::args().nth(1);
    match task.as_deref() {
        Some("codegen") => codegen(),
        Some(other) => bail!("unknown task {other:?}; expected `codegen`"),
        None => {
            eprintln!("usage: cargo xtask codegen");
            Ok(())
        }
    }
}

/// Repository root, derived from this crate's manifest directory.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

fn codegen() -> Result<()> {
    let root = workspace_root();
    let ast_path = root.join("vendor/typescript-go/_scripts/ast.json");
    let source = fs::read_to_string(&ast_path).with_context(|| {
        format!(
            "reading {}\n\nThe vendored submodule may not be initialized; run:\n  \
             git submodule update --init vendor/typescript-go",
            ast_path.display()
        )
    })?;

    let ast: AstDefinition =
        serde_json::from_str(&source).context("parsing ast.json against our schema model")?;

    println!(
        "loaded ast.json: {} kinds, {} bases, {} node definitions, {} aliases",
        ast.kinds.kind_names().len(),
        ast.bases.len(),
        ast.nodes.definitions.len(),
        ast.nodes.aliases.len(),
    );

    let out_dir = root.join("crates/tsr-ast/src/generated");
    fs::create_dir_all(&out_dir).context("creating generated output directory")?;

    write_generated(&out_dir.join("kind.rs"), &gen_kind::generate(&ast)?)?;
    write_generated(&out_dir.join("nodes.rs"), &gen_nodes::generate_nodes(&ast)?)?;
    write_generated(&out_dir.join("alias.rs"), &gen_nodes::generate_aliases(&ast)?)?;
    write_generated(&out_dir.join("visit.rs"), &gen_nodes::generate_visit(&ast)?)?;

    // A machine-readable record of what the generator saw, so the conformance test
    // can assert against upstream without re-parsing ast.json at test time.
    let manifest = serde_json::json!({
        "source": "vendor/typescript-go/_scripts/ast.json",
        "kind_count": ast.kinds.kind_names().len(),
        "kinds": ast.kinds.kind_names(),
        "node_count": ast.nodes.definitions.len(),
        "alias_count": ast.nodes.aliases.len(),
    });
    fs::write(
        out_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).context("serializing manifest")?,
    )
    .context("writing manifest.json")?;

    write_generated(&out_dir.join("mod.rs"), MOD_RS)?;

    println!("wrote {}", out_dir.display());
    Ok(())
}

const MOD_RS: &str = "//! Generated AST definitions.\n\
     //!\n\
     //! @generated by `cargo xtask codegen`. Do not edit by hand.\n\n\
     pub mod alias;\n\
     pub mod kind;\n\
     pub mod nodes;\n\
     pub mod visit;\n";

fn write_generated(path: &std::path::Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}
