[package]
name = "tsr-parser"
description = "The TypeScript parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tsr-core = { workspace = true }
tsr-ast = { workspace = true }
tsr-scanner = { workspace = true }
tsr-diagnostics = { workspace = true }

[dev-dependencies]
tsr-diagnostics = { workspace = true }

[lints]
workspace = true
