[package]
name = "tsr-printer"
description = "Prints the AST back to TypeScript source"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
bitflags = { workspace = true }
tsr-ast = { workspace = true }
tsr-core = { workspace = true }

[dev-dependencies]
tsr-parser = { workspace = true }

[lints]
workspace = true
