import { execFile, spawn } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { promisify } from 'node:util';

const run = promisify(execFile);

/** One reading of where the port stands. */
export type Reading = {
  /** Matched assertion lines. */
  matched: number;
  /** The denominator the suite counts. */
  total: number;
  /** matched/total as a percentage — the number the project steers by. */
  gradient: number;
  /** Whole cases passing the positional gate. */
  cases: number;
  /** The gate's denominator. */
  caseTotal: number;
  /** Commit the reading was taken at. */
  commit: string;
  /** Whether it came from a live run or from the committed snapshot. */
  source: 'coverage' | 'snapshot';
};

const SNAPSHOT = 'crates/tsr-conformance/snapshots/checker_types.snap';

/**
 * Parse the two figures out of the **snapshot's** `checker_types` summary.
 *
 * This reads the snapshot format, not the `coverage` binary's stdout. The two
 * are different and assuming otherwise is what broke the first version of this
 * file: `coverage` prints a per-suite *table* whose `checker_types` row carries
 * the gradient as a bare percentage, while the absolute line counts this loop
 * needs to compute a delta live only in the snapshot it writes as a side
 * effect. See [`runCoverage`].
 */
function parse(text: string): Omit<Reading, 'commit' | 'source'> {
  const lines = /Assertion lines:\s*(\d+)\/(\d+)/.exec(text);
  const cases = /Passed\s*:\s*(\d+)\/(\d+)/.exec(text);
  if (!lines || !cases) {
    throw new Error(
      'could not find `Assertion lines:` and `Passed :` in the checker_types summary — ' +
        'the report format changed and this parser needs updating',
    );
  }
  const matched = Number(lines[1]);
  const total = Number(lines[2]);
  return {
    matched,
    total,
    gradient: (matched / total) * 100,
    cases: Number(cases[1]),
    caseTotal: Number(cases[2]),
  };
}

async function commitOf(repo: string): Promise<string> {
  const { stdout } = await run('git', ['rev-parse', '--short', 'HEAD'], { cwd: repo });
  return stdout.trim();
}

/**
 * Measure the gradient **independently of anything the agent said**.
 *
 * This is the load-bearing part of the loop. An agent asked to report its own
 * progress can be wrong in good faith — this project's own history has several
 * numbers that were true of a different population than the one they were
 * quoted about — so the loop never reads a figure out of the agent's prose. It
 * runs the conformance binary and parses the summary, or, when `live` is
 * false, reads the committed snapshot the agent regenerates as part of its
 * gate discipline.
 *
 * `live` defaults to true and should stay that way: a snapshot is only as
 * fresh as the last time someone ran the gates, and an iteration that skipped
 * them would otherwise look like an iteration that made no progress.
 */
export async function measure(repo: string, live = true): Promise<Reading> {
  const commit = await commitOf(repo);
  if (!live) {
    const text = await readFile(`${repo}/${SNAPSHOT}`, 'utf8');
    return { ...parse(text), commit, source: 'snapshot' };
  }

  // Run the suite to regenerate the snapshot, then read the snapshot. The
  // binary's stdout is a table that does not carry absolute line counts, so
  // the snapshot is the only source for those — and running first is what
  // makes it fresh, which is the whole point of the live path.
  const stdout = await runCoverage(repo);
  const reading = { ...parse(await readFile(`${repo}/${SNAPSHOT}`, 'utf8')), commit };

  // **A control, not decoration.** The table and the snapshot are produced by
  // one run of one binary, so their gradients must agree; if they do not, the
  // snapshot on disk is not the one this run produced — a stale file left by a
  // failed write, or a `coverage` that errored after printing. Reporting a
  // stale number as a live measurement is exactly the failure this loop exists
  // to prevent, so it is loud rather than silent.
  const printed = /^checker_types\s+\S+\s+\S+\s+\S+\s+([\d.]+)%/m.exec(stdout);
  if (printed) {
    const fromTable = Number(printed[1]);
    if (Math.abs(fromTable - reading.gradient) > 0.02) {
      throw new Error(
        `coverage printed ${fromTable}% but the snapshot reads ` +
          `${reading.gradient.toFixed(2)}% — the snapshot was not regenerated by this run`,
      );
    }
  }
  return { ...reading, source: 'coverage' };
}

/**
 * Run the conformance binary, echoing cargo's progress as it goes, and return
 * its stdout.
 *
 * Its stdout is a per-suite table, e.g.
 *
 * ```text
 * checker_types                         2452/9538    25.71%      2906    69.03%
 * ```
 *
 * which is used only as a cross-check — the figures the loop steers by come
 * from the snapshot this run rewrites.
 *
 * `execFile` would be three lines shorter and would print nothing for the
 * minutes this takes — the same silence problem the agent stream has, in a
 * place where "is it compiling or is it wedged?" is the only question a
 * watcher has. Cargo writes its progress to stderr, so stderr is echoed live
 * and stdout is captured for the parser.
 */
function runCoverage(repo: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      'cargo',
      ['run', '--release', '-p', 'tsr-conformance', '--bin', 'coverage'],
      { cwd: repo },
    );
    let stdout = '';
    let lastProgress = '';

    child.stdout.on('data', (buffer: Buffer) => {
      stdout += buffer.toString();
    });
    child.stderr.on('data', (buffer: Buffer) => {
      for (const line of buffer.toString().split('\n')) {
        const trimmed = line.trim();
        // Cargo is chatty about crates it did not rebuild; only the phase
        // headings are worth a watcher's attention.
        if (!/^(Compiling|Building|Finished|Running|error|warning)/.test(trimmed)) continue;
        if (trimmed === lastProgress) continue;
        lastProgress = trimmed;
        process.stdout.write(`    [2m${trimmed.slice(0, 100)}[0m\n`);
      }
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`coverage exited ${code}`));
    });
  });
}

/** Whether the tree is clean and every commit is on the remote. */
export async function repoState(repo: string): Promise<{ clean: boolean; pushed: boolean }> {
  const { stdout: status } = await run('git', ['status', '--porcelain'], { cwd: repo });
  let pushed = true;
  try {
    const { stdout: ahead } = await run(
      'git',
      ['rev-list', '--count', '@{upstream}..HEAD'],
      { cwd: repo },
    );
    pushed = ahead.trim() === '0';
  } catch {
    // No upstream configured: not something the loop should fail on, but not
    // something it should silently claim either.
    pushed = false;
  }
  return { clean: status.trim() === '', pushed };
}
