//! Complete controls generated by pinned tsgo 5b1047d10d32e7d5b446be4de56b126ff42f82bb.
//! Owners separates require-call admission from syntactic JS import aliases;
//! Aliases separates lexical RHS owners and undefined export writes from real
//! errors on later typed writes, ordinary members and a shadowed exports value.

use tsr_conformance::{
    TestCase, diagnostics_suite, errors_baseline, types_baseline, types_producer,
};

#[test]
fn commonjs_module_values_match_every_native_assertion_and_diagnostic() {
    let mut failures = Vec::new();
    let mut assertions = 0;
    let mut diagnostics = 0;
    for (name, source, types, errors) in [
        (
            "owners",
            include_str!("fixtures/commonjs_assignment/Owners.ts"),
            include_str!("fixtures/commonjs_assignment/Owners.types"),
            "",
        ),
        (
            "descriptors",
            include_str!("fixtures/commonjs_assignment/Descriptors.ts"),
            include_str!("fixtures/commonjs_assignment/Descriptors.types"),
            include_str!("fixtures/commonjs_assignment/Descriptors.errors.txt"),
        ),
        (
            "aliases",
            include_str!("fixtures/commonjs_assignment/Aliases.ts"),
            include_str!("fixtures/commonjs_assignment/Aliases.types"),
            include_str!("fixtures/commonjs_assignment/Aliases.errors.txt"),
        ),
        (
            "unknown",
            include_str!("fixtures/commonjs_assignment/Unknown.ts"),
            include_str!("fixtures/commonjs_assignment/Unknown.types"),
            "",
        ),
        (
            "export-values",
            include_str!("fixtures/commonjs_assignment/ExportValues.ts"),
            include_str!("fixtures/commonjs_assignment/ExportValues.types"),
            "",
        ),
    ] {
        let case = TestCase::parse(&format!("probe/commonjs-{name}"), "control.ts", source);
        let expected = types_baseline::parse(types);
        let actual = types_producer::assertions_for_case(&case, &case.files.as_slice(), false);
        if actual.len() != expected.len() {
            failures.push(format!(
                "{name}: file population {} != {}",
                actual.len(),
                expected.len()
            ));
        }
        for (wanted, got) in expected.iter().zip(&actual) {
            assertions += wanted.assertions.len();
            let actual = got.iter().map(types_producer::Assertion::line).collect::<Vec<_>>();
            let expected = wanted
                .assertions
                .iter()
                .map(|assertion| assertion.text.clone())
                .collect::<Vec<_>>();
            if actual != expected {
                failures.push(format!(
                    "{name}: {}\nactual: {actual:?}\nexpected: {expected:?}",
                    wanted.file
                ));
            }
        }
        let mut expected = errors_baseline::parse(errors);
        let mut actual = diagnostics_suite::reported_for(&case);
        expected.sort_unstable();
        actual.sort_unstable();
        diagnostics += expected.len();
        if actual != expected {
            failures.push(format!("{name}: complete duplicate-aware diagnostics\nactual: {actual:?}\nexpected: {expected:?}"));
        }
    }
    println!(
        "complete native controls: {assertions} assertions, {diagnostics} diagnostic occurrences"
    );
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
